# Jvm Properties
java_version=17
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Environment Properties
minecraft_version=1.20.1
forge_version=47.4.6

# Mod Properties
mod_id=fpp
mod_name=Floatable Pressure Plates
mod_version=1.0.1
mod_authors=QiuShui1012
mod_description=Added a bunch of floatable variation of vanilla pressure plates.

# Maven Properties
maven_group=zh.qiushui.mod.fpp
archives_name=FloatablePressurePlates
